# Generated by Django 5.1.6 on 2025-03-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='places/images/')),
                ('adress', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
