# Generated by Django 5.1.6 on 2025-03-11 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_barr_bog'),
    ]

    operations = [
        migrations.AddField(
            model_name='barr',
            name='cost',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bog',
            name='cost',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='cost',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
