# Generated by Django 5.1.6 on 2025-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_adress_place_address_place_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='address',
        ),
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='adress',
            field=models.CharField(default='Direccion no especificada', max_length=150),
        ),
        migrations.AlterField(
            model_name='place',
            name='cost',
            field=models.CharField(default='No tiene costo', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(default='No tiene costo', upload_to='places/images/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True, default='No tiene Pagina'),
        ),
    ]
