# Generated by Django 5.1.6 on 2025-03-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_remove_place_adress_place_address_place_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(default='Dirección no especificada', max_length=255),
        ),
    ]
