# Generated by Django 5.1.6 on 2025-03-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_place_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barr',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='bog',
            name='adress',
        ),
        migrations.AddField(
            model_name='barr',
            name='address',
            field=models.CharField(default='Dirección no especificada', max_length=255),
        ),
        migrations.AddField(
            model_name='barr',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barr',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bog',
            name='address',
            field=models.CharField(default='Dirección no especificada', max_length=255),
        ),
        migrations.AddField(
            model_name='bog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barr',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='barr',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='barr',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/images/'),
        ),
        migrations.AlterField(
            model_name='barr',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='barr',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bog',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='places/images/'),
        ),
        migrations.AlterField(
            model_name='bog',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bog',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
