# Generated by Django 5.1.6 on 2025-04-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='barr',
        ),
        migrations.RemoveField(
            model_name='review',
            name='bog',
        ),
        migrations.RemoveField(
            model_name='review',
            name='place',
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(choices=[('medellin', 'Medellín'), ('bogota', 'Bogotá'), ('barranquilla', 'Barranquilla')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Barr',
        ),
        migrations.DeleteModel(
            name='Bog',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
