# Generated by Django 5.1.6 on 2025-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
