# Generated by Django 5.2.6 on 2025-10-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_place_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='place',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
