# Generated by Django 5.1.6 on 2025-05-19 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Evento', models.CharField(max_length=200)),
                ('Resumen', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='places/images/')),
                ('fecha', models.DateField()),
                ('Ciudad', models.CharField(max_length=200)),
            ],
        ),
    ]
